spring.application.name=seat-reservation

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/seat_reservation
spring.datasource.username=postgres
spring.datasource.password=admin#123

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId}] [%thread] %logger{36} - %msg%n